---
title: "Photophys Traces"
output: html_document
date: "2026-02-14"
---

```{r}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggh4x)
library(data.table)
library(stringr)
library(pvclust)
library(dendextend)
library(here)
```

# Photophys data loading 

```{r photophys}
photophys <- read.csv(here("Data","AS26_PhenotypingData_expt.csv"), row.names = 1)
load(here("Data","cbb_AS26_expt_1000bs.RData"))
sample_metadata <- read.csv(here("Data","AS26_MAPPmetadata_expt.csv"), check.names = F)
# cluster object from Dendrogram.Rmd is called cbb
clusterer <- cbb

# reshape to long
longphoto_shortie <- photophys %>% 
  select(-c(uni, metrix)) %>%
  pivot_longer(
    cols = -c(metric, stage, col),
    names_to = "SampleID",
    values_to = "Value"
  )
longphoto_shortie <- longphoto_shortie %>%
  filter(
    !(startsWith(SampleID, "t7") & grepl("icra|ahya", SampleID) & grepl("005", SampleID)),
    !(startsWith(SampleID, "t7") & grepl("aglo|aabr", SampleID) & grepl("002", SampleID))
  )

longphoto_shortie <- longphoto_shortie %>%
  mutate(
    SampleID_clean = SampleID %>%
      tolower() %>%
      str_replace("\\.processed\\.csv$", "") %>%
      str_replace("\\._?\\d{2,3}r$", "") %>%
      trimws()
  )

#check if duplicates
longphoto_shortie %>%
  count(SampleID_clean, stage, col, metric) %>%
  filter(n > 1)


longphoto_shortie_fixed <- longphoto_shortie %>%
  mutate(SampleID_clean = str_remove(SampleID_clean, "\\..*"),
         SampleID_clean = str_trim(SampleID_clean)) %>% #make sure no whitesapces at end of name or name issues
  filter(SampleID_clean %in% sample_metadata$UniqueID)#only want to keep samples that we ahve metadata for (removing any that werent already filtered out) 

# This shows you the rows that will be dropped
filtered_out_samples <- longphoto_shortie_fixed %>% 
  anti_join(sample_metadata, by = c("SampleID_clean" = "UniqueID"))

# Print the unique SampleIDs that are filtered out
print(unique(filtered_out_samples$SampleID_clean))

#check if duplicates per sample, stage/col/metric: YES
longphoto_shortie_fixed %>%
  count(SampleID_clean, stage, col, metric) %>%
  filter(n > 1)

#change cbb
dend_ids <- cbb$hclust$labels %>%
  tolower() %>%
  str_replace("\\.processed\\.csv$", "") %>%
  str_replace("\\._?\\d{2,3}r$", "") %>%
  trimws()

longphoto_shortie <- longphoto_shortie %>%
  filter(SampleID_clean %in% dend_ids)

# longphoto_wide <- longphoto_shortie %>%
#   pivot_wider(
#     names_from = metric,
#     values_from = Value
#   ) %>%
#   distinct(SampleID_clean, .keep_all = TRUE)
longphoto_wide <- longphoto_shortie %>%
  pivot_wider(
    id_cols = c(stage, col, SampleID, SampleID_clean),
    names_from = metric,
    values_from = Value
  )


longphoto_wide <- longphoto_wide[,1:18]
```

#make df with clusters 3-8
```{r}
cluster_results <- lapply(3:8, function(k) {
  clusters <- cutree(cbb$hclust, k = k)
  
  df <- data.frame(
    SampleID = names(clusters),
    Cluster = clusters
  )
  
  # Dynamically rename the 'Cluster' column to include the k value
  colnames(df)[2] <- paste0("Cluster_", k)
  return(df)
})

# Now they join cleanly without .x/.y because only 'SampleID' is shared
cluster_df_all <- Reduce(function(x, y) left_join(x, y, by = "SampleID"), cluster_results)

cluster_df_all <- cluster_df_all %>%
mutate(
    SampleID_clean = SampleID %>%
      tolower() %>%
      str_replace("\\.processed\\.csv$", "") %>%
      str_replace("\\._?\\d{2,3}r$", "") %>%
      trimws()
  )

# --- Merge cluster assignments into phenotype data ---
df_with_clusters <- longphoto_wide %>%
  left_join(cluster_df_all, by = "SampleID_clean")

# --- Check result ---
head(df_with_clusters)

head(longphoto_wide)
```

```{r}

# Assuming 'hc' is your hclust object and 'df' is your original data
# 1. Cut the tree into 4 clusters
clusters <- cutree(cbb$hclust, k = 3)


# 2. Add the cluster assignments to your original dataframe
cluster_df <- data.frame(
  SampleID = names(clusters),
  Cluster = as.factor(clusters)
)

cluster_df<- cluster_df %>%
  mutate(
    SampleID_clean = SampleID %>%
      tolower() %>%
      str_replace("\\.processed\\.csv$", "") %>%
      str_replace("\\._?\\d{2,3}r$", "") %>%
      trimws()
  )

df_with_clusters <- longphoto_wide %>%
  left_join(cluster_df, by = "SampleID_clean")


# 3. Pull out samples belonging to Cluster 1
cluster_1_samples <- df_with_clusters %>% dplyr::filter(Cluster == 1) %>% 
  distinct(SampleID_clean)

# 4. View the result
print(cluster_1_samples)

df_with_clusters[, 5:18] <- lapply(df_with_clusters[, 5:18], function(x) {
  as.numeric(as.character(x))
})

sum_photo <- df_with_clusters %>% 
  group_by(stage, col, Cluster) %>%
    summarise(across(where(is.numeric), mean, na.rm = TRUE ))

sum_photo_long <- sum_photo %>% 
   pivot_longer(
    cols = -c(stage, col, Cluster), # Selects all columns except "Metric"
    names_to = "Metric",
    values_to = "Value"
  ) 
# 
# # 1. Empirically 'pick' the significant clusters
# # alpha = 0.95 corresponds to the 95% confidence level
# signif_clusters <- pvpick(cbb, alpha = 0.98)
# 
# # 2. View the clusters and the samples within them
# print(signif_clusters$clusters)
# 
# # 3. See the AU p-values for these specific clusters
# print(signif_clusters$edges)
```

#Select Ks
```{r}
cluster_results <- lapply(1:9, function(k) {

  clusters <- cutree(cbb$hclust, k = k)

  data.frame(
    SampleID = names(clusters),
    Cluster = as.integer(clusters),
    k = k
  )
})


cluster_df_all <- bind_rows(cluster_results) %>%
  pivot_wider(
    names_from = k,
    values_from = Cluster,
    names_prefix = "K_"
  )

cluster_df_all <- cluster_df_all %>%
  mutate(
    SampleID_clean = SampleID %>%
      tolower() %>%
      str_replace("\\.processed\\.csv$", "") %>%
      str_replace("\\._?\\d{2,3}r$", "") %>%
      trimws()
  )

df_with_clusters <- longphoto_wide %>%
  left_join(cluster_df_all, by = "SampleID_clean")

df_with_clusters <- df_with_clusters %>%
  mutate(
    site = str_extract(SampleID_clean, "^t\\d+") %>%
      str_remove("t"),

    species = str_extract(SampleID_clean, "(?<=_)[:alpha:]+"),

    genotype = str_extract(SampleID_clean, "\\d+$"),

    GroupingProperty = paste(site, toupper(species), genotype, sep = "_")
  )


#save the cluster assignments w sample for ed50 and umap comaprisons

cluster_summary<- df_with_clusters %>%
  distinct(SampleID_clean, .keep_all = TRUE) %>% 
  select(SampleID_clean, site, species, genotype, K_1:K_2:K_3:K_4:K_5:K_6:K_7:K_8:K_9) 

cluster_summary%>% 
  write.csv(file = here("Data", "expt_data_clustered.csv"), row.names = FALSE)
```

# Plotting traces
```{r}
sub_photo <- sum_photo_long %>% 
  dplyr::filter(Metric != 'nTau1' & Metric !=  'nTau2' & Metric != 'nCon'& Metric != 'Fm' & Metric != 'Fo' & col != 'All' & col != 'Ratio12' & col != 'Ratio32' & col != 'Ratio42') %>% 
  dplyr::mutate(stage = as.numeric(as.character(stage))) %>% 
    dplyr::filter(stage >=1  & stage <= 27) %>% 
  arrange(stage)

sub_photo <- sub_photo %>%
  mutate(Cluster = factor(Cluster))

# 2. Extract the branch colors assigned by color_branches
# This pulls the unique colors used for the clusters in order
#extract_cols <- unique(get_leaves_branches_col(dend))

#cluster_cols <- c("1" = "#CC476B", "2" = "#9F7000", "3" = "#228B00", "4" = "#009681", "5" = "#0082CE","6" = "#B646C7")
# 3. Create a clean lookup table for your ggplot

ggplot(sub_photo) + 
  geom_line(aes(x = stage, y = Value, group = interaction(col, Cluster), colour = col)) + 
  facet_grid(Metric ~ Cluster, scales = "free_y") +
  theme_minimal() +
theme(
  plot.margin = margin(10, 20, 10, 10),
  strip.text = element_text(size = 6, ),
  axis.text.x = element_text(size = 6),
  axis.text.y = element_text(size = 6),
  axis.title = element_text(size = 8)
)
#ggsave(plot = last_plot(), filename = "Figures/Photophys_tracesbycluster.jpeg")
```
```{r}
#see if site and cluster are sig associated
table(cluster_summary$species, cluster_summary$K_3)
chisq.test(table(cluster_summary$species, cluster_summary$K_3)) #this breaks bc ahya and aabr arent in all groups

#this simulates
chisq.test(table(cluster_summary$species, cluster_summary$K_3), simulate.p.value = TRUE)

#can try fishers but that only works for two groups
fisher.test(table(cluster_summary$species, cluster_summary$K_2))

fisher.test(table(cluster_summary$species, cluster_summary$K_3), simulate.p.value = TRUE)


#site
table(cluster_summary$site, cluster_summary$K_3)
chisq.test(table(cluster_summary$site, cluster_summary$K_3)) #this breaks bc ahya and aabr arent in all groups

#this simulates
chisq.test(table(cluster_summary$site, cluster_summary$K_3), simulate.p.value = TRUE)

#can try fishers but that only works for two groups
fisher.test(table(cluster_summary$site, cluster_summary$K_3), simulate.p.value = TRUE)
```

